/*
 * generated by Xtext
 */
package org.xtext.arma.ui.contentassist

import org.xtext.arma.ui.contentassist.AbstractSQFProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SQFProposalProviderBUGGED extends AbstractSQFProposalProvider {
}
