/**
 * generated by Xtext
 */
package org.xtext.arma.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.xtext.arma.ui.contentassist.AbstractSQFProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SQFProposalProvider extends AbstractSQFProposalProvider 
{
    SQFProposalProvider()
    {
        super();
        System.out.println("Constructing SQFProposalProvider.");
    }
    //FIXME: Never called...
    @Override
    public void completeModel_Lines(EObject model, Assignment assignment, 
            ContentAssistContext context, ICompletionProposalAcceptor acceptor)
    {
        System.out.println("Proposing...");

        completeRuleCall(((RuleCall)assignment.getTerminal()), context, acceptor);
    }
    
    //FIXME: Never called...
    @Override
    public void completeCommandLeft_Name(EObject model, Assignment assignment, 
            ContentAssistContext context, ICompletionProposalAcceptor acceptor) 
    {
        System.out.println("Proposing...");
        //completeRuleCall(((RuleCall)assignment.getTerminal()), context, acceptor);
        acceptor.accept(createCompletionProposal("hello", context));
        
    }
    /*
    @Override
    public void complete_CommandLeft(EObject model, RuleCall ruleCall, 
            ContentAssistContext context, ICompletionProposalAcceptor acceptor) 
    {
        System.out.println("Proposing...");
        acceptor.accept(createCompletionProposal("hello", context));
        // subclasses may override
    }
    */
}
