/*
 * generated by Xtext
 */
package org.xtext.arma.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SQFUiModule extends org.xtext.arma.ui.AbstractSQFUiModule {
	public SQFUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
