/*
 * generated by Xtext 2.10.0
 */
package org.arma.xtext.ui.tests;

import com.google.inject.Injector;
import org.arma.xtext.config.ui.internal.ConfigActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class ConfigUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ConfigActivator.getInstance().getInjector("org.arma.xtext.Config");
	}

}
