/*
 * generated by Xtext
 */
package org.arma.xtext.ui.contentassist

import org.arma.xtext.ui.contentassist.AbstractSqfProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SqfProposalProvider extends AbstractSqfProposalProvider {
}
