/*
 * generated by Xtext
 * FIXME: This is being generated even though GenerateXtendStub = false
 */
package org.arma.xtext.ui.contentassist

import org.arma.xtext.ui.contentassist.AbstractSQFProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SQFProposalProvider extends AbstractSQFProposalProvider {
}
