/*
 * generated by Xtext
 */
package org.arma.xtext;
import org.arma.xtext.scoping.SQFJavaScopeProvider;
import org.arma.xtext.scoping.SqfGlobalScopeProvider;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SQFRuntimeModule extends org.xtext.arma.AbstractSQFRuntimeModule
{
    @Override
    public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider()
    {
        return SQFJavaScopeProvider.class;
    }
    
    @Override
    public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider()
    {
        return SqfGlobalScopeProvider.class;
    }
}
