/*
 * generated by Xtext
 */
package org.arma.xtext;
import org.arma.xtext.scoping.SqfJavaScopeProvider;
import org.arma.xtext.linking.SqfLinkingService;
import org.arma.xtext.scoping.SqfGlobalScopeProvider;
import org.eclipse.xtext.linking.ILinkingService;
import org.eclipse.xtext.linking.lazy.LazyLinker;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SqfRuntimeModule extends org.arma.xtext.AbstractSqfRuntimeModule
{
    @Override
    public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider()
    {
        return SqfJavaScopeProvider.class;
    }
    
    @Override
    public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider()
    {
        return SqfGlobalScopeProvider.class;
    }
    
    @Override
	public Class<? extends ILinkingService> bindILinkingService()
    {
		return SqfLinkingService.class;
	}
    
    @Override
	public Class<? extends org.eclipse.xtext.linking.ILinker> bindILinker()
    {
		return LazyLinker.class;
	}
}
