/*
 * generated by Xtext s
 */
package org.arma.xtext;

import org.arma.xtext.SQFStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SQFStandaloneSetup extends SQFStandaloneSetupGenerated 
{

    public static void doSetup() {
    	new SQFStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}

