/*
 * generated by Xtext
 */
package org.arma.xtext;

import org.arma.xtext.SqfStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SqfStandaloneSetup extends SqfStandaloneSetupGenerated 
{

    public static void doSetup() {
    	new SqfStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}

