/*
 * generated by Xtext
 */
package org.arma.xtext.ui;

import org.arma.xtext.ui.syntaxcoloring.DefaultHighlightingConfiguration;
import org.arma.xtext.ui.syntaxcoloring.StyleHighlightingCalculator;
import org.arma.xtext.ui.syntaxcoloring.StyleTokenToAttributeIdMapper;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SqfUiModule extends org.arma.xtext.ui.AbstractSqfUiModule 
{
	public SqfUiModule(AbstractUIPlugin plugin) 
	{
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () 
	{
	    return DefaultHighlightingConfiguration.class;
	}
	
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper()
	{
	    return StyleTokenToAttributeIdMapper.class;
	}
	
    public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator()
	{
	    return StyleHighlightingCalculator.class;
	}
	
	// contributed by org.eclipse.xtext.ui.generator.contentAssist.ContentAssistFragment
    @Override
	public Class<? extends org.eclipse.xtext.ui.editor.contentassist.IContentProposalProvider> bindIContentProposalProvider()
    {
        return org.arma.xtext.ui.contentassist.SqfJavaProposalProvider.class;
    }

    public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProvider()
    {
        return org.arma.xtext.ui.SqfEObjectDocumentationProvider.class;
    }
}
