/*
 * generated by Xtext 2.10.0
 */
package org.arma.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ConfigStandaloneSetup extends ConfigStandaloneSetupGenerated {

	def static void doSetup() {
		new ConfigStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
